### ISSUE TITLE
Enable localization of error msgs

### ISSUE THREAD

**Issue by jocker-il** [Choumiko/SmallFixes#1]
please add localization text for error messages so I can localize this mod,

thank you :)

**Comment by Choumiko** [comment]
The ones in https://github.com/Choumiko/SmallFixes/blob/master/config.lua ? These really should never be seen by a user, since that means i screwed up somewhere. And then i'd prefer if i understood them immediately. Or am i missing some messages?

**Comment by jocker-il** [comment]
Yes, those are the ones I meant. What I do when translating error messages is _add_ the hebrew to the original english text exactly for that reason, so the mod author (you or anyone else) can understand it too.

 If you think it's not necessary, I remove my request. I trust you know best.

side note: would be nice if documented the changes you make to #Factorio in this mod :)

10x
J.

**Comment by Choumiko** [comment]
No changes since last release in october. Should be somewhere in the Forums though

On the note of error messages: I'm not even sure if localization is possible in the loading phase (data.lua etc)

**Comment by jocker-il** [comment]
I meant in the readme file on github so the short description makes it possible to understand what that mod does when browsing repos

Sent from Samsung Mobile.

<div>-------- Original message --------</div><div>From: Choumiko notifications@github.com </div><div>Date:02/03/2016  21:46  (GMT+02:00) </div><div>To: Choumiko/SmallFixes SmallFixes@noreply.github.com </div><div>Cc: "The JoCKeR (IL)" jockeril@yahoo.com </div><div>Subject: Re: [SmallFixes] Enable localization of error msgs (#1) </div><div>
</div>No changes since last release in october. Should be somewhere in the Forums though

On the note of error messages: I'm not even sure if localization is possible in the loading phase (data.lua etc)
